name: CI/CD

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    name: Test (Node.js v${{ matrix.node }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.optional }}
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
        optional:
          - false
        include:
          # TODO: particle-usb doesn't support Node.js 14 and higher:
          # https://github.com/particle-iot/particle-usb/pull/47
          - node: 14
            optional: true
          - node: 16
            optional: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: npm-shrinkwrap.json
      - run: npm install
      - run: npm run lint
      - run: npm test
      # TODO: Disable integration tests for now as they require a Github token
      # - run: npm run integration:test
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: npm-shrinkwrap.json
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
